### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by kschmid** [jboxberger/synology-gitlab-ce#10]
Despite most stuff working fine, there is one issue, I couldn't resolve:
- the external url of the gitlab (e.g., one it provides the cloning URL) is: synology-gitlab-ce (which is not even a correct url)
- so I attempted to modify this:
1. ssh to NAS and bash into the docker container (as per above)
2. edit the external URL as per https://docs.gitlab.com/omnibus/settings/configuration.html
3. sudo docker exec -t "synology-gitlab-ce" bash -c "gitlab-ctl reconfigure"
4. sudo docker exec -t "synology-gitlab-ce" bash -c "gitlab-ctl restart"

Unfortunately, this didn't work: even though, there were no obvious error messages (there was a huge amount of output to "reconfigure"), when everything was finished, even after several minutes no access was possible, i.e., Gitlab was no longer available at the URL, it was available previously as this was the URL used for reconfiguration. 
(http://xyz.synology.me:30080/

However, I could successfully revert the process, luckily.

**Comment by kschmid** [comment]
I should clarify why this is still an issue: some elements like issues still have URLs that contain the bogus domain element. As a result: clicking on an issue for modifying it, does not work. Instead one has to click (error page result) and then manually edit the URL to go back to the correct server.  (I suppose there are similar problems with other parts beyond the issue tracker, but I have not fully tested.)

Any idea of what to change would be appreciated.

**Comment by jboxberger** [comment]
Thank you for the info, and again sorry for my late reply.  I have no solution for that. If you change the external_url with Port (as you need on synology) the container fails to boot because this fail internaly. If you change the external_url without port, then the links are technicaly correct but without the port you end up in the DSM. We need somehow to tell the Webserver inside thwe docker to run under another port, but the dthe docker port-mapping 30080:80 will fail.... this is a tricky one. I think this is a GitLab Bug, since other URLs are working fine without this setting.

This IS NOT THE SOLUTION, i was playing around with this but got no solutuion!
```
# enter container
sudo docker exec -it "synology-gitlab-ce" bash 

vi /etc/gitlab/gitlab.rb

# search for external_url and modify to your needs <port is optional> (NO EQUAL SIGN!!!)
# you need the port and the ending backslash
# between external_url and tha value is NO EQUAL SIGN!
# see this example:
external_url 'http://xpenology7:30080/'

# reconfig and restart
gitlab-ctl reconfigure
gitlab-ctl restart

```

**Comment by kschmid** [comment]
In the meantime, I completely remade the installation and as part of it, I figured it out.  (Sorry, should of posted, but thought, project was abandoned.)
Here is the docker compose, I am using now. The GITLAB_OMNIBUS_CONFIG is the culprit, it seams. (At least, this is what my notes say ,-) )
The gitlab.xx is the url without port. 


```
version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.xx'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.xx'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:20080'
      - '443:20443'
      - '22:20022'
    volumes:
      - '/volume1/docker/gitlab-ce/config:/etc/gitlab'
      - '/volume1/docker/gitlab-ce/logs:/var/log/gitlab'
      - '/volume1/docker/gitlab-ce/data:/var/opt/gitlab'
    shm_size: '256m'
```
